<?php
 /**
 * A PHTML Template file which contains the Home.
 */
 
 /**
 * A  which contains the Home
 *
 * @category   Design
 * @package    Design
 * @author     Tim Steinbrecher
 * @version    Release: 1.0
 */
 ?>
<div class="mdl-grid mdl-components">
	<div class="mdl-cell mdl-cell--8-col">
		<span class="docs-text-styling">
            <h1 class="mdl-components__classname" id="layout-section/layout"><i class="material-icons">search</i>Suche</h1>
         </span>
		<form action="Search" method="POST">
			<div class="mdl-textfield mdl-js-textfield">
				<input class="mdl-textfield__input" type="text" id="search" name="search">
				<label class="mdl-textfield__label" for="search">Suchen</label>
			</div>
		</form>
	</div>
	<div class="mdl-cell mdl-cell--4-col">
	</div>
</div>