<?php
 /**
 * A PHTML Template file file which contains the Upload
 */
 
/**
 * A Template which contains the Upload
 *
 * @category   Design
 * @package    Design
 * @author     Tim Steinbrecher
 * @version    Release: 1.0
 */
 ?>
<div class="mdl-grid mdl-components">
	<div class="mdl-cell mdl-cell--8-col">
		<span class="docs-text-styling">
            <h1 class="mdl-components__classname" id="layout-section/layout"><i class="material-icons">file_upload</i>upload</h1>
         </span>
		<form method="POST" action="/Upload" class="dropzone" id="document-upload"></form>
	</div>
	<div class="mdl-cell mdl-cell--4-col">
	</div>
</div>